export const ADD_BLE = 'ADD_BLE';
export const INITIALIZE_LIST = 'INITIALIZE_LIST';
export const CHANGE_STATUS = 'CHANGE_STATUS';
export const CONNECTED_BLE = 'CONNECTED_BLE';
export const DISCONNECTED_BLE = 'DISCONNECTED_BLE';
export const SELECT_ROW = 'SELECT_ROW';
export const UPDATE_HEARTBEAT = 'UPDATE_HEARTBEAT';
